project:
  type: website
  post-render:
    - "rsync -av site-apps/. _site/"

format:
  revealjs:
    theme: simple
    css: custom.css
    slide-number: true
    transition: fade
    controls: true
    overview: true 
