project:
  type: website
  post-render:
    - "rsync -av site-apps/. _site/"

format:
  revealjs:
    theme: simple
    slide-number: true
    transition: fade
    incremental: true
    controls: true
    overview: true
